In [1]:
#part 1
#slide 4-6
x <- list(a=1:10)
lapply(x, sqrt)

$a
 [1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

In [4]:
#slide 7
y <- list(a = sample.int(100, 10), b = 10:20, c = rnorm(5))
y
sapply(y, mean)

$a
 [1] 62 45 67 79 95 33 11 97 24 50

$b
 [1] 10 11 12 13 14 15 16 17 18 19 20

$c
[1] -0.4076035 -0.2573620  0.2451778  2.3963426 -0.8616730

a          b          c 
56.3000000 15.0000000  0.2229764

In [8]:
#slide 8
library(datasets)
head(CO2)
s <- split(CO2, CO2$uptake)

 sapply(s, function(x) {
     colMeans(x[, c("conc", "uptake")])
 })

Plant Type   Treatment  conc uptake
1 Qn1   Quebec nonchilled  95  16.0  
2 Qn1   Quebec nonchilled 175  30.4  
3 Qn1   Quebec nonchilled 250  34.8  
4 Qn1   Quebec nonchilled 350  37.2  
5 Qn1   Quebec nonchilled 500  35.3  
6 Qn1   Quebec nonchilled 675  39.2

7.7  9.3  10.5 10.6 11.3 11.4  12 12.3  12.5  13  ... 40.3  40.6  41.4 
conc   95.0 95.0 95.0 95.0 95.0 175.0 95 250.0 500.0 350 ... 250.0 500.0 837.5
uptake  7.7  9.3 10.5 10.6 11.3  11.4 12  12.3  12.5  13 ...  40.3  40.6  41.4
       41.8  42.1  42.4   42.9  43.9  44.3   45.5  
conc   350.0 350.0 1000.0 500.0 675.0 1000.0 1000.0
uptake  41.8  42.1   42.4  42.9  43.9   44.3   45.5

In [12]:
#slide 9-10
z <- c(a = sample.int(100, 30))
fact <- gl(3, 10)
tapply(z, fact, mean)

1    2    3 
55.5 43.7 42.6

In [15]:
#slide 11-12
a <- array(sample.int(200), c(2, 2, 10))
a
apply(a, 1, mean)
apply(a, 2, mean)

, , 1

     [,1] [,2]
[1,]   39  141
[2,]  130  132

, , 2

     [,1] [,2]
[1,]  183    8
[2,]   36   78

, , 3

     [,1] [,2]
[1,]  172   81
[2,]   16  119

, , 4

     [,1] [,2]
[1,]  103  151
[2,]  191   35

, , 5

     [,1] [,2]
[1,]   73  117
[2,]  184  182

, , 6

     [,1] [,2]
[1,]  112   86
[2,]   94   79

, , 7

     [,1] [,2]
[1,]  164   10
[2,]  121   42

, , 8

     [,1] [,2]
[1,]   40   20
[2,]  158  146

, , 9

     [,1] [,2]
[1,]   41   19
[2,]   84  155

, , 10

     [,1] [,2]
[1,]   74  109
[2,]    9   82

[1]  87.15 103.65

[1] 101.2  89.6

In [20]:
#slide 13-14
a <- c(sample.int(15,5))
a
b <- c(sample.int(15,5))
b
mapply(function(v1,v2) v1*v2, a, b)

[1]  7  9 14  4 13

[1]  3 13  8  7  6

[1]  21 117 112  28  78

In [21]:
#slide 15-16
fun <- function(a, b){
    sqrt(a*b + 10)
}
m <- sample.int(500, 15)
vfun <- Vectorize(fun, c("a",  "b"))
vfun(1:15, m)

[1] 16.093477  7.615773  4.358899 22.135944 49.396356 54.589376 50.645829
 [8] 48.020829 66.685831 56.656862 13.638182 61.562976 59.983331 32.984845
[15] 50.892043

In [5]:
#part 2
#slide 3
library(stringr)
str_c("A", "group", "of", "dragons", "is", "called", "a", "thunder.", sep = " ")
str_length("A group of dragons is called a thunder.")
dragon <- "A group of dragons is called a thunder."
str_sub(dragon, start = 12, end = 18)
str_sub(dragon, start = -8, end = 38)

[1] "A group of dragons is called a thunder."

[1] 39

[1] "dragons"

[1] "thunder"

In [9]:
#slide 4
str_dup(":)", 1:5)
str_trim("         white   space       ", side = "both")
str_pad("emphasis", width = 12, side = "both", pad = "*")

[1] ":)"         ":):)"       ":):):)"     ":):):):)"   ":):):):):)"

[1] "white   space"

[1] "**emphasis**"

In [14]:
#slide 5
str_detect(dragon, "thunder")
str_locate(dragon, "called")
str_locate_all(dragon, "e")
str_extract(dragon, "of dragons")
str_extract_all(dragon, "e")

[1] TRUE

start end
[1,] 23    28

[[1]]
     start end
[1,]    27  27
[2,]    37  37

[1] "of dragons"

[[1]]
[1] "e" "e"

In [20]:
#slide 6
str_replace(dragon, "dragons", "crows")
str_replace_all(dragon, "e", "ooo")
str_split(dragon, "is")
str_split_fixed(dragon, "is", 10)

[1] "A group of crows is called a thunder."

[1] "A group of dragons is calloood a thundooor."

[[1]]
[1] "A group of dragons " " called a thunder."

[,1]                [,2]               [,3] [,4] [,5] [,6] [,7] [,8] [,9]
[1,] A group of dragons   called a thunder.                                   
     [,10]
[1,]